export const RELAY_HEADER_BATCH_SIZE = 100;
export const SCAN_MEMPOOL_CHUNK_SIZE = 500;
export const SCAN_MEMPOOL_CHUNK_INTERVAL_DELAY = 250;
export const SCAN_BLOCKS_CHUNK_SIZE = 10;
export const SCAN_BLOCK_TXS_INTERVAL_DELAY = 100;
export const SUBMIT_RELAY_RECOVERY_TX_INTERVAL_DELAY = 100;
export const SUBMIT_RELAY_CHECKPOINT_INTERVAL_DELAY = 100;
export const RELAY_DEPOSIT_BLOCKS_SIZE = 1100; // 500 blocks
export const RETRY_DELAY = 100; // 1 second
export const ITERATION_DELAY = {
  RELAY_SIGNATURES_INTERVAL: 3000,
  TRACK_MEMORY_LEAK: 10000,
  SIMULATOR_INTERVAL: 5000,
};
